apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-backend
  template:
    metadata:
      labels:
        app: currency-backend
    spec:
      containers:
        - name: currency-backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@db:{{ .Values.postgres.port }}/{{ .Values.postgres.dbName }}"
            - name: DB_CONFIG_HOST
              value: {{ .Values.backend.host }}
            - name: DB_CONFIG_PORT
              value: {{ .Values.postgres.port }}
            - name: DB_CONFIG_USERNAME
              value: {{ .Values.postgres.user }}
            - name: DB_CONFIG_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: DB_CONFIG_DATABASE
              value: {{ .Values.postgres.dbName }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: currency-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
