apiVersion: v1
kind: Service
metadata:
  name: backend-metrics
  namespace: default
  labels:
    app: currency-backend
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
  selector:
    app: currency-backend

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: currency-backend-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: currency-backend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s